/**
 * SRIYAAN METALS — WASM migration runner (development tooling).
 *
 * Drives @prisma/schema-engine-wasm directly with the pg driver
 * adapter. Exists because the sandbox cannot download Prisma's
 * native schema-engine binary (binaries.prisma.sh is unreachable);
 * in normal environments `npx prisma migrate dev` does exactly the
 * same work. The migration files it produces are standard Prisma
 * migrations, fully compatible with `prisma migrate deploy`.
 *
 * Usage:
 *   node scripts/migrate.mjs create <name>   # diff schema → create migration dir
 *   node scripts/migrate.mjs apply           # apply pending migrations
 *   node scripts/migrate.mjs status          # list migration dirs
 */
import "./env.mjs";
import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import { PrismaPg } from "@prisma/adapter-pg";
import { bindMigrationAwareSqlAdapterFactory } from "@prisma/driver-adapter-utils";
import { SchemaEngine } from "@prisma/schema-engine-wasm";

const ROOT = resolve(import.meta.dirname, "..");
const SCHEMA_PATH = join(ROOT, "prisma", "schema.prisma");
const MIGRATIONS_DIR = join(ROOT, "prisma", "migrations");
const LOCKFILE_PATH = join(MIGRATIONS_DIR, "migration_lock.toml");

function loadMigrationsList() {
  mkdirSync(MIGRATIONS_DIR, { recursive: true });

  const migrationDirectories = readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((d) => ({
      path: d.name,
      migrationFile: {
        path: "migration.sql",
        content: {
          tag: "ok",
          value: readFileSync(join(MIGRATIONS_DIR, d.name, "migration.sql"), "utf8"),
        },
      },
    }));

  return {
    baseDir: MIGRATIONS_DIR,
    lockfile: {
      path: "migration_lock.toml",
      content: existsSync(LOCKFILE_PATH) ? readFileSync(LOCKFILE_PATH, "utf8") : null,
    },
    shadowDbInitScript: "",
    migrationDirectories,
  };
}

async function makeEngine() {
  const factory = new PrismaPg({ connectionString: process.env.DATABASE_URL });
  // The engine expects an *error-proofed* adapter factory whose calls
  // return { ok, value } results — exactly what this official helper
  // produces (it is what Prisma's own CLI uses internally).
  const errorProofed = bindMigrationAwareSqlAdapterFactory(factory);
  const schema = readFileSync(SCHEMA_PATH, "utf8");
  return SchemaEngine.new(
    { datamodels: [["prisma/schema.prisma", schema]] },
    () => {}, // event callback (progress logs)
    errorProofed,
  );
}

const filters = { externalTables: [], externalEnums: [] };

const command = process.argv[2];
const engine = await makeEngine();

try {
  if (command === "create") {
    const name = process.argv[3];
    if (!name) throw new Error("Usage: node scripts/migrate.mjs create <name>");
    const schema = readFileSync(SCHEMA_PATH, "utf8");
    const list = loadMigrationsList();
    // Diff source: empty for the first migration, otherwise the live
    // database (avoids the shadow-DB requirement of the `migrations`
    // source; valid because we always apply before creating the next).
    // Diff source: empty for the first migration; afterwards the
    // schema as of the last commit (datamodel→datamodel diff — no
    // shadow DB or introspection needed). Requires committing the
    // schema together with each generated migration, which is the
    // standard Prisma workflow anyway.
    let from = { tag: "empty" };
    if (list.migrationDirectories.length > 0) {
      const { execSync } = await import("node:child_process");
      const prevSchema = execSync("git show HEAD:prisma/schema.prisma", {
        cwd: ROOT,
        encoding: "utf8",
      });
      from = {
        tag: "schemaDatamodel",
        files: [{ path: "prisma/schema.prisma", content: prevSchema }],
      };
    }
    const out = await engine.diff({
      from,
      to: {
        tag: "schemaDatamodel",
        files: [{ path: "prisma/schema.prisma", content: schema }],
      },
      script: true,
      exitCode: false,
      filters,
    });
    const script = out.stdout ?? "";
    if (!script.trim()) {
      console.log("No changes — migration would be empty.");
    } else {
      const stamp = new Date()
        .toISOString()
        .replace(/[-:TZ.]/g, "")
        .slice(0, 14);
      const dirName = `${stamp}_${name}`;
      const dir = join(MIGRATIONS_DIR, dirName);
      mkdirSync(dir, { recursive: true });
      writeFileSync(join(dir, "migration.sql"), script);
      if (!existsSync(LOCKFILE_PATH)) {
        writeFileSync(
          LOCKFILE_PATH,
          `# Please do not edit this file manually\n# It should be added in your version-control system (e.g., Git)\nprovider = "postgresql"\n`,
        );
      }
      console.log(`Created migration: ${dirName}`);
    }
  } else if (command === "apply") {
    const out = await engine.applyMigrations({
      migrationsList: loadMigrationsList(),
      filters,
    });
    const applied = out.appliedMigrationNames ?? [];
    console.log(
      applied.length
        ? `Applied: ${applied.join(", ")}`
        : "Database is up to date — nothing to apply.",
    );
  } else if (command === "status") {
    const list = loadMigrationsList();
    console.log(`Migrations on disk: ${list.migrationDirectories.length}`);
    for (const d of list.migrationDirectories) console.log(` - ${d.path}`);
    console.log(`DB version: ${await engine.version()}`);
  } else {
    throw new Error("Usage: node scripts/migrate.mjs <create <name>|apply|status>");
  }
} finally {
  engine.free();
}
